### ISSUE TITLE
Please increase limit for blocks

### ISSUE THREAD

**Issue by recytec** [makamys/MAtmos-2020-Zen#1] opened 2021-03-12 23:00 UTC
Since my minecraft is heavly modded and has a block count over 4096, matmos having errors since it probably cannot handle the amount of blocks.

Maybe you can fix it for next patch

[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: java.lang.ArrayIndexOutOfBoundsException: 4696
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.data.modules.BlockCountModule.increment(BlockCountModule.java:82)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.data.modules.BlockCountModule.increment(BlockCountModule.java:73)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.data.modules.BlockCountModule.increment(BlockCountModule.java:30)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.data.scanners.ScannerModule.inputAndReturnBlockMeta(ScannerModule.java:309)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.data.scanners.ScannerModule.input(ScannerModule.java:291)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.data.scanners.ScanVolumetric.doRoutine(ScanVolumetric.java:58)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.data.scanners.Scan.routine(Scan.java:54)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.data.scanners.ScannerModule.process(ScannerModule.java:211)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.data.modules.ModuleRegistry.process(ModuleRegistry.java:189)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.core.sound.Simulacrum.onTick(Simulacrum.java:87)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.Matmos.onTick(Matmos.java:231)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.lib.eu.ha3.mc.haddon.forge.ForgeBase.onTickLiteLoaderStyle(ForgeBase.java:143)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.lib.eu.ha3.mc.haddon.forge.ForgeBase.onRenderTick(ForgeBase.java:111)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at eu.ha3.matmos.ForgeMatmos.onRenderTick(ForgeMatmos.java:34)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1766_ForgeMatmos_onRenderTick_RenderTickEvent.invoke(.dynamic)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:58:58] [Client thread/INFO] [STDERR]: [eu.ha3.matmos.data.modules.ModuleRegistry:process:192]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by juraj-hrivnak** [comment] 2021-04-30 11:08
This is an issue with Matmos itself and not the sound pack.

It has been already fixed.
https://github.com/makamys/MAtmos/issues/2

**Comment by makamys** [comment] 2021-07-29 01:14
That's right. Closing as duplicate of makamys/MAtmos#2.

**Closed as completed by makamys** 2021-07-29 01:14 UTC
